import { portrait } from '../portraits.js';
import { rating } from '../prematch.js';
import { geeResistance } from '../gee.js';
import { shipBetTotal } from './bet-totals.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const credits=n=>Math.round(n/100).toLocaleString();
const roles={pilot:['Pilot','Handling'],gunner:['Gunner','Gunnery'],engineer:['Engineer','Engineering'],ops:['Ops','Defence']};
const doctrines={Reference:'Duelist',Knife:'Knife fighter',Counter:'Counterpuncher'};
const shipArt=`<svg class="market-vessel" viewBox="0 0 160 80" aria-hidden="true"><path class="vessel-guide" d="M8 60H150M80 8V74M28 68L132 16"/><path class="vessel-wing" d="M23 59L139 20L85 65L70 50Z"/><path class="vessel-hull" d="M70 50L139 20L84 56L85 65Z"/><path class="vessel-ridge" d="M42 56L139 20L74 45Z"/><path class="vessel-engine" d="M70 50L84 56L76 62L62 56Z"/><path class="vessel-stripe" d="M82 43L118 29M87 47L123 30"/></svg>`;
function shipPanel(s,i,f,draft,wager){
 const selected=(wager?.side??draft.side)===i;
 return `<article class="market-ship t${i} ${selected?'backed':''}" role="button" tabindex="${wager?'-1':'0'}" data-side="${i}" aria-pressed="${selected}" aria-disabled="${!!wager}" aria-label="${esc(s.name)}, ${Math.round(f.odds[i]*100)} percent win odds${wager?', betting locked':', select to bet'}">
 <header><div class="market-identity"><span class="hb-eyebrow">SHIP ${i+1} / ${esc(doctrines[s.style]||s.style)}</span><h2 title="${esc(s.name)}">${esc(s.name)}</h2><span class="market-choice"><i aria-hidden="true">${selected?'✓':'+'}</i>${wager?selected?'YOUR BET · LOCKED':'BETTING LOCKED':selected?'SELECTED':'SELECT SHIP'}</span></div>${shipArt}<div class="market-odds"><b>${Math.round(f.odds[i]*100)}<small>%</small></b><span>WIN ODDS</span></div></header>
 <div class="market-crew">${s.crew.map(c=>{
  const art=portrait(c.name),r=rating(c.skill),g=geeResistance(c),[station,skill]=roles[c.station];
  return `<section class="market-person" aria-label="${esc(c.name)}, ${station}"><div class="market-person-head"><div class="hb-face" style="--face:url('/assets/portraits/${art.file}');--face-color:${art.color}" aria-hidden="true"></div><div><span class="market-station">${station}</span><b title="${esc(c.name)}">${esc(c.name)}</b></div></div><div class="market-stat"><div><span>${skill}</span><b>${r}<small>/99</small></b></div><div class="market-bar" role="meter" aria-label="${skill}" aria-valuemin="1" aria-valuemax="99" aria-valuenow="${r}"><i style="--fill:${r/99*100}%"></i><em aria-hidden="true"></em></div></div><div class="market-stat market-gee"><div><span title="Lowers the chance of blackouts or death at 7+ g">G resist</span><b>${g}<small>/10</small></b></div><div class="market-bar" role="meter" aria-label="Gee resistance" aria-valuemin="1" aria-valuemax="10" aria-valuenow="${g}"><i style="--fill:${g*10}%"></i></div></div></section>`;
 }).join('')}</div><footer class="market-panel-foot"><span>CREW · 50 = AVG</span><div data-market-total="${i}">${shipBetTotal(f.betting?.bySide[i],credits)}</div></footer></article>`;
}
export function renderBetting({fight:f,player,draft,wager:w,busy=false,authenticated=true}){
 const stake=Math.round(Number(draft.amount)*100),p=draft.side===null?null:f.odds[draft.side];
 const profit=p==null||!Number.isFinite(stake)?null:Math.round(stake*.95*(1-p)/p/100)*100;
 return `<section class="hb-match-dossier match-console betting-desk"><header class="match-console-head"><div><span class="hb-eyebrow">MATCH ${String(f.sequence).padStart(4,'0')} / LIVE BROADCAST</span><h1>${w?'Bet locked':'Choose your ship'}</h1></div><div class="hb-window"><span>FIGHT STARTS IN</span><b data-countdown></b></div></header><div class="match-console-body"><div class="market-fleet" role="group" aria-label="Choose a ship to bet on">${f.ships.map((s,i)=>shipPanel(s,i,f,draft,w)).join('')}</div><div class="market-method"><span>${f.oddsSamples} matchup simulations · fixed odds</span><span>5% margin on profit</span></div></div><footer class="match-action-bar">${!authenticated?'<div class="hb-guest-bet"><div><b>Watch free. Sign in to bet.</b><p>New accounts start with 500 credits. Your progress follows you across devices.</p></div><button class="hb-primary" data-do="account">Create account / sign in ↗</button></div>':w?`<div class="hb-locked-wager"><div><span>BET LOCKED</span><b>${credits(w.stake)} cr on ${esc(f.ships[w.side].name)}</b></div><div><span>WIN PROFIT</span><strong>+${credits(w.payout-w.stake)} cr</strong><small>${credits(w.payout)} cr total return</small></div><span class="locked-mark">✓</span></div>`:`<form class="hb-wager-form" data-form="wager"><label for="stake">STAKE / CR <span>Max ${credits(player.maxBet)}</span><input id="stake" name="stake" type="number" inputmode="numeric" min="1" step="1" max="${Math.floor(player.maxBet/100)}" value="${esc(draft.amount)}" required></label><div class="hb-wager-quote"><span>WIN PROFIT</span><b id="profit">${profit==null?'Choose a ship':'+ '+credits(profit)+' cr'}</b><small id="after-stake">${credits(player.balance-(Number.isFinite(stake)?stake:0))} cr remaining</small></div><button type="submit" class="hb-primary" data-do="place-bet" ${draft.side===null||busy?'disabled':''}>${busy?'Placing…':'Lock bet'}<span aria-hidden="true">↗</span></button><p>One bet per fight · bets are final · watching is free</p></form>`}</footer></section>`;
}
