import { build } from 'esbuild';
import { writeFile, mkdir, cp, rm } from 'node:fs/promises';
await mkdir('viewer2/js/live', { recursive: true });
await build({ entryPoints: ['viewer2/js/live/client.js'], bundle: true, format: 'esm', outfile: 'viewer2/js/live/client.bundle.js', minify: true, target: 'es2022' });
const url=process.env.VITE_CONVEX_URL||process.env.CONVEX_URL||(process.env.VERCEL_ENV==='production'?'https://glad-dogfish-932.convex.cloud':'');
if(!url)throw new Error('Set VITE_CONVEX_URL to the target Convex deployment before building.');
await writeFile('viewer2/live-config.json',JSON.stringify({convexUrl:url}));
await rm('dist',{recursive:true,force:true});
await cp('viewer2','dist',{recursive:true,filter:path=>!/(?:^|\/)(matches|cards|tools)(?:\/|$)/.test(path)});
console.log(`Built live client${url?' with configured Convex deployment':'; Convex URL is not configured'}. Legacy recordings are excluded from the deployment.`);
